platform :ios, '12.0'

target 'TL-PestIdentify' do
  pod 'LookinServer', :configurations => ['Debug']
  pod 'YYModel'
  pod 'AgriPestClient', :git => 'https://github.com/lukecc00/AgriPest-IOS-SDK.git', :tag => 'v1.0.63'
  pod 'WCDB.objc'
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.0'
end
