platform :ios, '12.0'

target 'TL-PestIdentify' do
  pod 'LookinServer', :configurations => ['Debug']
  pod 'YYModel'
  pod 'AFNetworking'
  pod 'WCDB.objc'
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.0'
end
