platform :ios, '12.0'

target 'TL-PestIdentify' do
  pod 'LookinServer', :configurations => ['Debug']
  pod 'YYModel'
  pod 'AgriPestClient', :git => 'https://github.com/Biscoffee/AgriPest-IOS-SDK.git', :tag => 'v1.0.109'
  pod 'WCDB.objc', :git => 'https://github.com/Tencent/wcdb.git', :branch => 'master'
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.0'
end